### PR TITLE
feat: use cash.min.js on the page instead of CDN

### PR DESCRIPTION
**Pull request by raisedadead**
The CDN is potentially having some CORS errors. Using the script on the auth page instead for now.

/cc @scissorsneedfoodtoo @ojeytonwilliams

### CODE REVIEW

**Comment by raisedadead** [comment]
This is live in production BTW. Making the PR for review.

**Comment by raisedadead** [comment]
See: https://forum.freecodecamp.org/t/cant-signup-to-free-code-camp/422916/15

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sorry I'm just seeing this now. Thanks for deploying such a quick fix :+1:

**Comment by raisedadead** [comment]
Yep - I do not like it though.

**Comment by scissorsneedfoodtoo** [comment]
I know what you mean. I'd like to take another pass at this and just use vanilla JS. If I remember correctly, Cash is just hiding or showing some elements, and maybe fetching something, so it should be possible.

**Comment by raisedadead** [comment]
Sounds like a plan. But no rush, I know you are pretty swamped already.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, sounds good. I'll add it to the Trello board so we have a place to track progress on this.

**Pull request merged**
