### PR TITLE
feature (UI): Icons added to sign in screen #49687

### PR DESCRIPTION
**Pull request by Wenodh**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes freeCodeCamp/freeCodeCamp#49687

image
image
image

### CODE REVIEW

**Comment by raisedadead** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by ahmadabdolsaheb** [comment]
Thanks for the pr. Here are a few recommendations:
- icons need to be on the left side of the text.
- icons need to be a single color.( color of the text)
- icons need to flip color on hover.
-  github logo should be the [invertocat version](https://github.com/logos)
- email option also needs an icon for consistency
- logos should not require attribution. They need to be from completely free sources or from the company's design style guide.

**Comment by Wenodh** [comment]
image
image
image

**Comment by Wenodh** [comment]
Updated as per your suggestions, For Google unfortunately I didn't find a better icon.

**Comment by ahmadabdolsaheb** [comment]
Updated the page background color, buttons backgrounds, to adhere to the providers' design style guide.

Screenshot 2023-03-28 at 3 02 07 PM

**Comment by ahmadabdolsaheb** [comment]
Screenshot 2023-03-28 at 3 41 45 PM

**Comment by Ankit1696** [comment]
Looks great thanks for making it.

**Pull request merged**
